// Auto-generated by create-project.sh — do not edit manually
import type { Router } from "express";
import authRouter from "./modules/auth/routes";
import dashboardRouter from "./modules/dashboard/routes";
import comercialRouter from "./modules/comercial/routes";
import operacionesRouter from "./modules/operaciones/routes";
import subproductosRouter from "./modules/subproductos/routes";
import novaRouter from "./modules/nova/routes";
import settingsRouter from "./modules/settings/routes";
import kpisRouter from "./modules/kpis/routes";

export const moduleRouters: Record<string, Router> = {
"auth": authRouter,
  "dashboard": dashboardRouter,
  "comercial": comercialRouter,
  "operaciones": operacionesRouter,
  "subproductos": subproductosRouter,
  "nova": novaRouter,
  "settings": settingsRouter,
  "kpis": kpisRouter,
};
